/*
 * ImageType
 *
 * Version 1.0
 * Author: Benni
 *
 * Dient zur Identifizierung jedes LoadedImage Objektes �ber den ImageHandler
 */
package uni.bombenstimmung.de.backend.images;

public enum ImageType {

    	//INTRO / MENU
	IMAGE_INTRO_PIC,
	IMAGE_MENU_PIC,
	IMAGE_MENU_TITLE,
	IMAGE_OPTIONS_PIC,
	
	//INGAME
    	IMAGE_INGAME_GRAS,
    	IMAGE_INGAME_WALL,
    	IMAGE_INGAME_BLOCK,
    	IMAGE_INGAME_BORDER,
    	
	//LOBBY
	IMAGE_LOBBY_ARROW_RIGHT,
	IMAGE_LOBBY_ARROW_RIGHT_BIGGER,
	IMAGE_LOBBY_ARROW_LEFT_BIGGER,
	IMAGE_LOBBY_ARROW_LEFT,
	IMAGE_LOBBY_MAPSELECTION_PLATZHALTER_1,
	IMAGE_LOBBY_MAPSELECTION_PLATZHALTER_2,
	IMAGE_LOBBY_MAPSELECTION_PLATZHALTER_3,
	IMAGE_LOBBY_SKINSELECTION_PLATZHALTER_1,
	IMAGE_LOBBY_SKINSELECTION_PLATZHALTER_2,
	IMAGE_LOBBY_SKINSELECTION_PLATZHALTER_3,
	IMAGE_LOBBY_CROWN,
	IMAGE_LOBBY_CHECKMARK,
	
	//INGAME
    	IMAGE_INGAME_YELLOWGRAS,
    	IMAGE_INGAME_BOMB,
    	IMAGE_INGAME_LIGHTTILE,
    	IMAGE_INGAME_LAVA_BLOCK,
    	IMAGE_INGAME_LAVA_FLOOR,
    	IMAGE_INGAME_LAVA_WALL,
    	INGAME_SKIN_01,
    	INGAME_SKIN_01_WASTED,
    	IMAGE_INGAME_BOMB_EX1,
    	IMAGE_INGAME_BOMB_EX2,
    	IMAGE_INGAME_BOMB_EX3,
    	IMAGE_INGAME_UPGRADE_TEMP,
    	IMAGE_INGAME_UPGRADE_ITEM_BOMB,
    	IMAGE_INGAME_UPGRADE_ITEM_SHOE,
    	IMAGE_INGAME_UPGRADE_ITEM_FIRE,
    	IMAGE_INGAME_BOMB_EX2_NS,
    	IMAGE_INGAME_BOMB_EX3_O,
    	IMAGE_INGAME_BOMB_EX3_W,
    	IMAGE_INGAME_BOMB_EX3_S,
    	IMAGE_INGAME_BOMB_EX3_N,
    	
	//LOBBY UND INGAME
	IMAGE_INGAME_ICON,
	IMAGE_INGAME_ICON_BLUE,
	IMAGE_INGAME_ICON_GELB,
	IMAGE_INGAME_ICON_PINK;
	
}
