/*
 * ImageType
 *
 * Version 1.0
 * Author: Benni
 *
 * Dient zur Identifizierung jedes LoadedImage Objektes �ber den ImageHandler
 */
package uni.bombenstimmung.de.backend.images;

public enum ImageType {

    	//INTRO / MENU
	IMAGE_INTRO_PIC,
	IMAGE_MENU_PIC,
	IMAGE_MENU_TITLE,
	IMAGE_OPTIONS_PIC,
	
	//INGAME
    	IMAGE_INGAME_GRAS,
    	IMAGE_INGAME_WALL,
    	IMAGE_INGAME_BLOCK,
    	IMAGE_INGAME_BORDER,
    	
	//LOBBY
	IMAGE_LOBBY_ARROW_RIGHT,
	IMAGE_LOBBY_ARROW_RIGHT_BIGGER,
	IMAGE_LOBBY_ARROW_LEFT_BIGGER,
	IMAGE_LOBBY_ARROW_LEFT,
	IMAGE_LOBBY_MAPSELECTION_PLATZHALTER_1,
	IMAGE_LOBBY_MAPSELECTION_PLATZHALTER_2,
	IMAGE_LOBBY_MAPSELECTION_PLATZHALTER_3,
	IMAGE_LOBBY_SKINSELECTION_PLATZHALTER_1,
	IMAGE_LOBBY_SKINSELECTION_PLATZHALTER_2,
	IMAGE_LOBBY_SKINSELECTION_PLATZHALTER_3,
	IMAGE_LOBBY_CROWN,
	IMAGE_LOBBY_CHECKMARK;
	
}
